### ISSUE TITLE
Can't find the Recipe Tab 

### ISSUE THREAD

**Issue by pewblaze** [orlouge/amphitrite-coffer#2]
So i can't find the Recipe Tab with REI? Or am i doing something wrong?
![2022-01-24_15 08 44](https://user-images.githubusercontent.com/96242065/150798137-25f3c622-c1c4-46a3-8f20-02e7a4603f20.png)
 
Mod Loader: Fabric
Version: 1.18.1

**Comment by orlouge** [comment]
You could previously see the recipe list by clicking on "Block Loot Drop" or whatever tab is currently selected, which shows all the tabs. Now I added the coffer as a workstation so that the tab also appears when you check its usages. In that screenshot you're checking its recipe though (use U/right click instead of R/left click).
